spring:
  application:
    name: spring security 01
  thymeleaf:
    cache: true
  security:
    user:
      name: user
      password: user123
      roles: USER
  messages:
    basename: i18n/messages
    encoding: utf-8
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    database: H2
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:tcp://localhost/~/test"
    username: sa
    password:
    type: com.zaxxer.hikari.HikariDataSource
  sql:
    init:
      platform: h2
#      schema-locations: classpath:sql/schema.sql
#      data-locations: classpath:sql/data_new.sql
      encoding: UTF-8
server:
  port: 8080
jwt:
  header: token
  issuer: prgrms
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  expiry-seconds: 60

